# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "首页"
  url = "#about"
  weight = 10

[[main]]
  name = "发表"
  url = "#featuredPublications"
  weight = 20

[[main]]
  name = "著作"
  url = "#authoredBooks"
  weight = 30

[[main]]
  name = "项目"
  url = "#researchProjects"
  weight = 40

[[main]]
  name = "奖励"
  url = "#academicAwards"
  weight = 45

[[main]]
  name = "服务"
  url = "#journalRoles"
  weight = 47

[[main]]
  name = "会议"
  url = "#conferenceReports"
  weight = 50

#[[main]]
#  name = "Blog"
#  url = "blog/"
#  weight = 40

#[[main]]
#  name = "Contact"
#  url = "#contact"
# weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
##    url = "files/cv_era/resume.html"
#    url = "files/cv.pdf"
#    weight = 60
